### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by samuel-lucas6** [judofyr/sodium.nim#1]
Hi @judofyr, I'm currently trying to tidy up the bindings linked on the libsodium website. If this library is still maintained, then please let me know; otherwise, the link to this library will [likely](https://github.com/jedisct1/libsodium-doc/pull/156#issuecomment-1067834246) be removed from the [bindings](https://doc.libsodium.org/bindings_for_other_languages) page to help users find up to date and maintained bindings.

**Comment by judofyr** [comment]
This is not maintained anymore. I’ll happily add someone else to the repo if they want to maintain it.

**Comment by samuel-lucas6** [comment]
Thanks for letting me know.

**Comment by samuel-lucas6** [comment]
I'm going to close this to help keep track of who hasn't replied yet. Obviously feel free to reopen it after the PR has gone through :) However, I'd recommend archiving the repository if you want to make it clear that it's no longer maintained.
